# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8027ac831c7e63bdc8637221e1f5c13c9345d957af343410b8ebfb096f4b8085635807de607ebb8cfc421c0b33676f912fc03ded094445da92e241ddebe146f7

test:
  secret_key_base: bb96403b63518ab1f67264444b0eb1f8496fbaf41c378970658cefa65d95431c77218524a20b79bd40b8734ceccc92327f4f8fd8dae8d8991a3b0b6b905ff0ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
